In [1]:
import json
from pathlib import Path
import numpy as np
import pandas as pd

In [2]:
SRC=Path.cwd().absolute(); TASK=SRC.parent; ROOT=TASK.parent
INPUT=TASK/'input'; OUTPUT=TASK/'output'
CFG=json.loads((ROOT/'config.json').read_text()); SEED=CFG['seed']; np.random.seed(SEED)

In [3]:
from prepare_data import panelize, prepare

In [4]:
raw=(INPUT/'import'/'e001_raw.csv').read_bytes()

In [5]:
panel, audit=panelize(raw, CFG['data'])
coverage=prepare(panel, CFG, CFG['evaluation'], OUTPUT)

In [6]:
audit['windows']=coverage
(OUTPUT/'audit.json').write_text(json.dumps(audit, indent=2))
display(pd.DataFrame(coverage).T)
display(pd.DataFrame.from_dict(audit['year_counts'], orient='index', columns=['plot_count']))

           windows  plots
one_train     1458    162
one_val        648    162
one_test       648    162
path_test      324    162

      plot_count
1982         162
1983         162
1984         162
1985         162
1986         162
1987         162
1988         162
1989         162
1990         162
1991         162
1992         162
1993         162
1994         162
1995         162
1996         162
1997         162
1998         162
1999         162
2000         162
2001         162
2002         162
2003         162
2004         162